apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jfi1pddfu-go 
  janus-idp.io/tekton: jfi1pddfu-go
  backstage.io/kubernetes-id: jfi1pddfu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jfi1pddfu-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml