apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jfi1pddfu-go
  janus-idp.io/tekton: jfi1pddfu-go
  backstage.io/kubernetes-id: jfi1pddfu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jfi1pddfu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
